# networks:
#   default:
#     name: 5gcore-net

services: 
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: open5gs
  amf:
    image: gradiant/open5gs:2.7.5
    command: 
      - open5gs-amfd
    ports:
      - 9090:9090
    volumes:
    - ./config/amf.yaml:/opt/open5gs/etc/open5gs/amf.yaml
    restart : on-failure
    
  ausf:
    image: gradiant/open5gs:2.7.5
    command: 
      - open5gs-ausfd
    volumes:
    - ./config/ausf.yaml:/opt/open5gs/etc/open5gs/ausf.yaml
    restart : on-failure
    
  bsf:
    image: gradiant/open5gs:2.7.5
    command: open5gs-bsfd
    restart : on-failure
    volumes:
    - ./config/bsf.yaml:/opt/open5gs/etc/open5gs/bsf.yaml
    
  nrf:
    image: gradiant/open5gs:2.7.5
    command: open5gs-nrfd
    restart : on-failure
    volumes:
    - ./config/nrf.yaml:/opt/open5gs/etc/open5gs/nrf.yaml 
    
  nssf:
    image: gradiant/open5gs:2.7.5
    command: open5gs-nssfd   
    restart : on-failure
    volumes:
    - ./config/nssf.yaml:/opt/open5gs/etc/open5gs/nssf.yaml 
    
  pcf:
    image: gradiant/open5gs:2.7.5
    command: 
      - open5gs-pcfd
    volumes:
    - ./config/pcf.yaml:/opt/open5gs/etc/open5gs/pcf.yaml
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart : on-failure
    
  # scp:
    # image: gradiant/open5gs:2.7.5
    # command: open5gs-scpd
    # environment:
      # DB_URI: mongodb://mongo/open5gs
    # restart: on-failure
    
  smf:
    image: gradiant/open5gs:2.7.5
    volumes:
    - ./config/smf.yaml:/opt/open5gs/etc/open5gs/smf.yaml
    ports:
      - 9091:9090
    command: open5gs-smfd
    restart : on-failure 
    
  udm:
    image: gradiant/open5gs:2.7.5
    restart: on-failure
    volumes:
    - ./config/udm.yaml:/opt/open5gs/etc/open5gs/udm.yaml
    command: 
      - open5gs-udmd
    
  udr:
    image: gradiant/open5gs:2.7.5
    restart: on-failure
    environment:
      DB_URI: mongodb://mongo/open5gs
    volumes:
    - ./config/udr.yaml:/opt/open5gs/etc/open5gs/udr.yaml
    command: 
      - open5gs-udrd
    
  upf:
    image: gradiant/open5gs:2.7.5
    user: root
    command:
      - open5gs-upfd
    privileged: true
    restart: on-failure
    volumes:
    - ./config/upf.yaml:/opt/open5gs/etc/open5gs/upf.yaml
    ports:
      - 2152:2152
    
  webui:
    image: gradiant/open5gs-webui:2.7.5
    restart: on-failure
    environment:
      DB_URI: mongodb://mongo/open5gs
      NODE_ENV: development
    ports:
      - 9999:9999
