#logger:
#  file:
#    path: /var/local/log/open5gs/nssf.log
#  level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.

svf:
  sbi:
    server:
      - address: 127.0.0.99
        port: 7777
    client:
#      scp:
#        - uri: http://127.0.0.200:7777
      nrf:
        - uri: http://172.18.0.10:7777
